"""In-memory sample order dataset for Northstar Retail Co. Support Deflection MVP."""

ORDERS_DB = [
    {
        "order_id": "ORD-1001",
        "customer_name": "Alice Smith",
        "product_name": "Northstar Trail Runner Pro",
        "size": "9.5",
        "status": "Processing",
        "carrier": "FedEx",
        "tracking_number": "FX-987654321-US",
        "estimated_delivery": "2026-08-18",
    },
    {
        "order_id": "ORD-1002",
        "customer_name": "Bob Johnson",
        "product_name": "Northstar Urban High-Top",
        "size": "11.0",
        "status": "Shipped",
        "carrier": "UPS",
        "tracking_number": "1Z9999999999999999",
        "estimated_delivery": "2026-08-16",
    },
    {
        "order_id": "ORD-1003",
        "customer_name": "Charlie Davis",
        "product_name": "Northstar Air Flex Low",
        "size": "8.0",
        "status": "Out for Delivery",
        "carrier": "USPS",
        "tracking_number": "9400100000000000000000",
        "estimated_delivery": "2026-08-14",
    },
    {
        "order_id": "ORD-1004",
        "customer_name": "Diana Prince",
        "product_name": "Northstar Marathon Elite",
        "size": "7.5",
        "status": "Delivered",
        "carrier": "DHL Express",
        "tracking_number": "DHL-1234567890",
        "estimated_delivery": "2026-08-12",
    },
    {
        "order_id": "ORD-1005",
        "customer_name": "Evan Wright",
        "product_name": "Northstar Leather Casual Sneaker",
        "size": "10.5",
        "status": "Processing",
        "carrier": "FedEx",
        "tracking_number": "FX-456789123-US",
        "estimated_delivery": "2026-08-19",
    },
]

SHOES_DB = [
    {
        "id": "shoe-1",
        "brand": "adidas",
        "name": "adidas Samba Indoor",
        "sku": "AD-SAMBA",
        "price": 9000,
        "currency": "KES",
        "color": "White / Black / Gum Brown",
        "stockStatus": "in_stock",
        "totalStock": 24,
        "originalStock": 24,
        "sizes": [
            {"size": "US 7", "quantity": 3},
            {"size": "US 8", "quantity": 6},
            {"size": "US 9", "quantity": 8},
            {"size": "US 10", "quantity": 5},
            {"size": "US 11", "quantity": 2},
            {"size": "US 12", "quantity": 0},
        ],
        "imagePlaceholder": "images/Adidas Unisex Adult Samba Indoor Shoe (1).jpg",
    },
    {
        "id": "shoe-2",
        "brand": "New Balance",
        "name": "New Balance 327",
        "sku": "NB-327",
        "price": 8000,
        "currency": "KES",
        "color": "White / Navy Blue",
        "stockStatus": "in_stock",
        "totalStock": 18,
        "originalStock": 18,
        "sizes": [
            {"size": "US 7", "quantity": 2},
            {"size": "US 8", "quantity": 4},
            {"size": "US 9", "quantity": 5},
            {"size": "US 10", "quantity": 4},
            {"size": "US 11", "quantity": 3},
            {"size": "US 12", "quantity": 0},
        ],
        "imagePlaceholder": "images/New Balance 327 Shoes.jpg",
    },
    {
        "id": "shoe-3",
        "brand": "adidas",
        "name": "adidas Campus 00s",
        "sku": "AD-CAMP00S",
        "price": 8500,
        "currency": "KES",
        "color": "Beige / White Stripes",
        "stockStatus": "low_stock",
        "totalStock": 5,
        "originalStock": 20,
        "sizes": [
            {"size": "US 7", "quantity": 0},
            {"size": "US 8", "quantity": 2},
            {"size": "US 9", "quantity": 2},
            {"size": "US 10", "quantity": 1},
            {"size": "US 11", "quantity": 0},
            {"size": "US 12", "quantity": 0},
        ],
        "imagePlaceholder": "images/adidas campus 00s.jpg",
    },
    {
        "id": "shoe-4",
        "brand": "Puma",
        "name": "Puma Smash V2 Low-Top",
        "sku": "PM-SMASHV2",
        "price": 7500,
        "currency": "KES",
        "color": "Black / White",
        "stockStatus": "in_stock",
        "totalStock": 15,
        "originalStock": 15,
        "sizes": [
            {"size": "US 7", "quantity": 2},
            {"size": "US 8", "quantity": 4},
            {"size": "US 9", "quantity": 5},
            {"size": "US 10", "quantity": 3},
            {"size": "US 11", "quantity": 1},
            {"size": "US 12", "quantity": 0},
        ],
        "imagePlaceholder": "images/Puma Unisex Adults Smash V2 Low-Top Sneakers.jpg",
    },
    {
        "id": "shoe-5",
        "brand": "Nike",
        "name": "Air Jordan 4 Retro",
        "sku": "NK-AJ4",
        "price": 15000,
        "currency": "KES",
        "color": "White / Cement Grey / Black",
        "stockStatus": "low_stock",
        "totalStock": 4,
        "originalStock": 20,
        "sizes": [
            {"size": "US 7", "quantity": 0},
            {"size": "US 8", "quantity": 1},
            {"size": "US 9", "quantity": 2},
            {"size": "US 10", "quantity": 1},
            {"size": "US 11", "quantity": 0},
            {"size": "US 12", "quantity": 0},
        ],
        "imagePlaceholder": "images/download (18).jpg",
    },
    {
        "id": "shoe-6",
        "brand": "Santoni",
        "name": "Casual Suede Santoni",
        "sku": "ST-CASUAL",
        "price": 3500,
        "currency": "KES",
        "color": "Navy Blue / Orange Script",
        "stockStatus": "in_stock",
        "totalStock": 12,
        "originalStock": 12,
        "sizes": [
            {"size": "US 40", "quantity": 2},
            {"size": "US 41", "quantity": 3},
            {"size": "US 42", "quantity": 4},
            {"size": "US 43", "quantity": 2},
            {"size": "US 44", "quantity": 1},
            {"size": "US 45", "quantity": 0},
        ],
        "imagePlaceholder": "images/_Casual Sued Santoni_🔥🔥🔥__Available Now_ ✅__Sizes Available____40 41 42 43 44 45____Quality_💯📌__@3500___DELIVERY ALSO AVAILABLE_👟📦🛵.jpg",
    },
    {
        "id": "shoe-7",
        "brand": "Puma",
        "name": "Puma Urban Leather Sneaker",
        "sku": "PM-URBAN",
        "price": 6500,
        "currency": "KES",
        "color": "Navy Blue / Grey",
        "stockStatus": "in_stock",
        "totalStock": 10,
        "originalStock": 10,
        "sizes": [
            {"size": "US 7", "quantity": 1},
            {"size": "US 8", "quantity": 3},
            {"size": "US 9", "quantity": 4},
            {"size": "US 10", "quantity": 2},
            {"size": "US 11", "quantity": 0},
            {"size": "US 12", "quantity": 0},
        ],
        "imagePlaceholder": "images/download (19).jpg",
    },
    {
        "id": "shoe-8",
        "brand": "Puma",
        "name": "Puma Clyde Classic Grey",
        "sku": "PM-CLYDE",
        "price": 5500,
        "currency": "KES",
        "color": "Light Grey / White Sole",
        "stockStatus": "in_stock",
        "totalStock": 8,
        "originalStock": 8,
        "sizes": [
            {"size": "US 7", "quantity": 1},
            {"size": "US 8", "quantity": 2},
            {"size": "US 9", "quantity": 3},
            {"size": "US 10", "quantity": 2},
            {"size": "US 11", "quantity": 0},
            {"size": "US 12", "quantity": 0},
        ],
        "imagePlaceholder": "images/download (20).jpg",
    },
]
