"""In-memory sample order dataset for Northstar Retail Co. Support Deflection MVP."""

ORDERS_DB = [
    {
        "order_id": "ORD-1001",
        "customer_name": "Alice Smith",
        "product_name": "Northstar Trail Runner Pro",
        "size": "9.5",
        "status": "Processing",
        "carrier": "FedEx",
        "tracking_number": "FX-987654321-US",
        "estimated_delivery": "2026-08-18",
    },
    {
        "order_id": "ORD-1002",
        "customer_name": "Bob Johnson",
        "product_name": "Northstar Urban High-Top",
        "size": "11.0",
        "status": "Shipped",
        "carrier": "UPS",
        "tracking_number": "1Z9999999999999999",
        "estimated_delivery": "2026-08-16",
    },
    {
        "order_id": "ORD-1003",
        "customer_name": "Charlie Davis",
        "product_name": "Northstar Air Flex Low",
        "size": "8.0",
        "status": "Out for Delivery",
        "carrier": "USPS",
        "tracking_number": "9400100000000000000000",
        "estimated_delivery": "2026-08-14",
    },
    {
        "order_id": "ORD-1004",
        "customer_name": "Diana Prince",
        "product_name": "Northstar Marathon Elite",
        "size": "7.5",
        "status": "Delivered",
        "carrier": "DHL Express",
        "tracking_number": "DHL-1234567890",
        "estimated_delivery": "2026-08-12",
    },
    {
        "order_id": "ORD-1005",
        "customer_name": "Evan Wright",
        "product_name": "Northstar Leather Casual Sneaker",
        "size": "10.5",
        "status": "Processing",
        "carrier": "FedEx",
        "tracking_number": "FX-456789123-US",
        "estimated_delivery": "2026-08-19",
    },
]
